version: 2
jobs:
    build-duo-contract-wrapper:
        working_directory: /home/circleci/duo-contract-wrapper
        docker: 
            - image: circleci/node:8.11.1
        steps:
            - run: git clone https://github.com/FinBook/duo-contract-wrapper.git /home/circleci/duo-contract-wrapper
            - run: cd /home/circleci/duo-contract-wrapper
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
    build-duo-admin:
        working_directory: /home/circleci/duo-admin
        docker: 
            - image: circleci/node:8.11.1
        steps:
            - run: git clone https://github.com/FinBook/duo-admin.git /home/circleci/duo-admin
            - run: cd /home/circleci/duo-admin
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install npm wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
    test:
        working_directory: /home/circleci/duo-app   
        docker: 
            - image: circleci/node:8.11.1 
        steps:
            - checkout
            - run:
                name: Install npm wee
                command: npm install
            - run:
                name: Test
                command: npm test
workflows:
    version: 2
    build_and_test:
        jobs:
            - build-duo-contract-wrapper
            - build-duo-admin
            - test:
                requires:
                    - build-duo-contract-wrapper
                    - build-duo-admin
                filters:
                    branches:
                        only: master