version: 2
jobs:
    test:
        working_directory: /home/circleci/duo-app
        docker:
            - image: circleci/node:8.11.1
        steps:
            - checkout
            - run:
                  name: Install npm
                  command: npm install
            - run:
                  name: coverage
                  command: npm test -- -w 1 --coverage --forceExit --detectOpenHandles
            - run:
                  name: post coverage
                  command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
    schedule_deploy:
        triggers:
            - schedule:
                  cron: '0 4 * * *'
                  filters:
                      branches:
                          only: master
        jobs:
            - test
